import pg from 'pg';
import { config } from './config';
import type { EventRow, EventStats, GuestRow } from '../shared/types';

// Postgres. Los tipos se ajustan para que el resto de la app reciba lo mismo que antes:
// conteos como número y fechas como texto ISO.
pg.types.setTypeParser(20, (v) => Number(v)); // int8 (COUNT)
pg.types.setTypeParser(1184, (v) => new Date(v).toISOString()); // timestamptz

export const pool = new pg.Pool({ connectionString: config.databaseUrl, max: 10 });

type Conn = pg.Pool | pg.PoolClient;

export async function query<T = Record<string, unknown>>(sql: string, params: unknown[] = [], conn: Conn = pool): Promise<T[]> {
  return (await conn.query(sql, params)).rows as T[];
}

export async function one<T = Record<string, unknown>>(sql: string, params: unknown[] = [], conn: Conn = pool): Promise<T | undefined> {
  return (await query<T>(sql, params, conn))[0];
}

/** Ejecuta y devuelve cuántas filas cambió. */
export async function exec(sql: string, params: unknown[] = [], conn: Conn = pool): Promise<number> {
  return (await conn.query(sql, params)).rowCount ?? 0;
}

export async function tx<T>(fn: (c: pg.PoolClient) => Promise<T>): Promise<T> {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const result = await fn(client);
    await client.query('COMMIT');
    return result;
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

// Migraciones en orden. Cada una se aplica una sola vez (tabla schema_migrations).
const migrations: string[] = [
  `
  CREATE TABLE events (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text NOT NULL,
    date          text NOT NULL,
    time          text NOT NULL,
    venue         text NOT NULL,
    address       text NOT NULL DEFAULT '',
    dress_code    text NOT NULL DEFAULT '',
    maps_url      text NOT NULL DEFAULT '',
    wa_template   text NOT NULL,
    email_subject text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
  );

  CREATE TABLE guests (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    name            text NOT NULL,
    business        text NOT NULL DEFAULT '',
    phone           text,
    email           text,
    token           text NOT NULL UNIQUE,
    email_status    text NOT NULL DEFAULT 'pending',
    email_sent_at   timestamptz,
    email_error     text,
    wa_status       text NOT NULL DEFAULT 'pending',
    wa_queued_at    timestamptz,
    wa_message_id   text,
    wa_sent_at      timestamptz,
    wa_error        text,
    checked_in_at   timestamptz,
    checked_in_role text,
    checked_in_by   text,
    created_at      timestamptz NOT NULL DEFAULT now()
  );

  CREATE UNIQUE INDEX guests_event_phone ON guests(event_id, phone) WHERE phone IS NOT NULL;
  CREATE INDEX guests_event ON guests(event_id);
  CREATE INDEX guests_wa_status ON guests(wa_status);
  CREATE INDEX guests_wa_message ON guests(wa_message_id);

  CREATE TABLE kv (
    key   text PRIMARY KEY,
    value jsonb NOT NULL
  );
  `,
  // Difusiones: mensajes de texto por WhatsApp a los invitados de un evento. Los destinatarios se fijan al
  // crearla y cada uno lleva su propio estado de envío.
  `
  CREATE TABLE broadcasts (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    audience    text NOT NULL,
    message     text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
  );

  CREATE TABLE broadcast_recipients (
    broadcast_id integer NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
    guest_id     integer NOT NULL REFERENCES guests(id) ON DELETE CASCADE,
    status       text NOT NULL DEFAULT 'queued',
    message_id   text,
    sent_at      timestamptz,
    error        text,
    PRIMARY KEY (broadcast_id, guest_id)
  );

  CREATE INDEX broadcast_recipients_status ON broadcast_recipients(broadcast_id, status);
  CREATE INDEX broadcast_recipients_message ON broadcast_recipients(message_id);
  `,
];

/** Crea o actualiza las tablas. Un candado evita que dos procesos migren a la vez. */
export async function initDb() {
  await tx(async (c) => {
    await c.query('SELECT pg_advisory_xact_lock(724119)');
    await c.query('CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())');
    const done = new Set((await query<{ version: number }>('SELECT version FROM schema_migrations', [], c)).map((r) => r.version));
    for (let v = 0; v < migrations.length; v++) {
      if (done.has(v + 1)) continue;
      await c.query(migrations[v]);
      await c.query('INSERT INTO schema_migrations (version) VALUES ($1)', [v + 1]);
    }
  });
}

export const nowIso = () => new Date().toISOString();

export async function kvGet<T>(key: string, fallback: T): Promise<T> {
  const row = await one<{ value: T }>('SELECT value FROM kv WHERE key = $1', [key]);
  return row ? { ...fallback, ...row.value } : fallback;
}

export async function kvSet(key: string, value: unknown) {
  await exec('INSERT INTO kv (key, value) VALUES ($1, $2) ON CONFLICT (key) DO UPDATE SET value = excluded.value', [key, JSON.stringify(value)]);
}

// ── Consultas compartidas ────────────────────────────────────────

export const getEvent = (id: number) => one<EventRow>('SELECT * FROM events WHERE id = $1', [id]);

export const getGuest = (id: number) => one<GuestRow>('SELECT * FROM guests WHERE id = $1', [id]);

export const getGuestByToken = (token: string) => one<GuestRow>('SELECT * FROM guests WHERE token = $1', [token]);

export const listGuests = (eventId: number) =>
  query<GuestRow>('SELECT * FROM guests WHERE event_id = $1 ORDER BY lower(name), id', [eventId]);

export async function eventStats(eventId: number): Promise<EventStats> {
  const row = await one<EventStats>(
    `SELECT
       count(*)                                                                 AS "total",
       count(*) FILTER (WHERE email_status = 'sent')                            AS "emailSent",
       count(*) FILTER (WHERE email_status = 'failed')                          AS "emailFailed",
       count(*) FILTER (WHERE wa_status = 'queued')                             AS "waQueued",
       count(*) FILTER (WHERE wa_status IN ('sent','delivered','read'))         AS "waSent",
       count(*) FILTER (WHERE wa_status IN ('delivered','read'))                AS "waDelivered",
       count(*) FILTER (WHERE wa_status = 'read')                               AS "waRead",
       count(*) FILTER (WHERE wa_status IN ('failed','no_whatsapp','uncertain')) AS "waProblems",
       count(*) FILTER (WHERE checked_in_at IS NOT NULL)                        AS "checkedIn"
     FROM guests WHERE event_id = $1`,
    [eventId],
  );
  return row!;
}
